accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pages.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('flowers/', include('flowers.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flowers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.FlowerListView.as_view(), name='flower_list'),
    path('<int:pk>/', views.FlowerDetailView.as_view(), name='flower_detail'),
    path('new/', views.FlowerCreateView.as_view(), name='flower_create'),
    path('<int:pk>/edit/', views.FlowerUpdateView.as_view(), name='flower_update'),
    path('<int:pk>/delete/', views.FlowerDeleteView.as_view(), name='flower_delete')
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUser(AbstractUser):
    city = models.CharField(max_length=200)

flowers/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth import get_user_model


# Create your models here.
class Flower(models.Model):
    title = models.CharField(max_length=225)
    seller = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    description = models.TextField()
    price = models.IntegerField()
    cover = models.ImageField(upload_to='covers/', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('flower_detail', args=[self.id])


class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    flower = models.ForeignKey(Flower, on_delete=models.CASCADE, related_name='comments')
    fullname = models.CharField(max_length=128, null=True)
    email = models.EmailField(null=True)
    text = models.TextField()
    datetime_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    recommend = models.BooleanField(default=True)

    def __str__(self):
        return self.text

    def get_author_name(self):
        try:
            return self.user.username
        except AttributeError:
            return self.fullname

    def get_absolute_url(self):
        return reverse('flower_detail', args=[self.flower.id]) + f'#{self.id}'

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'city',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'city',)

flowers/forms.py
from django import forms
from .models import Flower, Comment


class FlowerCreation(forms.ModelForm):
    class Meta:
        model = Flower
        fields = ('title', 'description', 'price', 'cover')


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'recommend',)


class AnonymousCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('fullname', 'email', 'text', 'recommend',)

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
# Create your views here.
from .forms import CustomUserCreationForm


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')

flowers/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Flower
from .forms import FlowerCreation, UserCommentForm, AnonymousCommentForm


class FlowerListView(generic.ListView):
    queryset = Flower.objects.order_by('-id')
    model = Flower
    template_name = 'flowers/flower_list.html'
    context_object_name = 'flowers'
    paginate_by = 4


class FlowerDetailView(generic.DetailView):
    model = Flower
    template_name = 'flowers/flower_detail.html'
    context_object_name = 'flower'

    def get_form_class(self):
        user = self.request.user
        return UserCommentForm if user.is_authenticated else AnonymousCommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.filter(is_active=True)
        context['form'] = self.get_form_class()()
        return context

    def post(self, *args, **kwargs):
        request = self.request
        form = self.get_form_class()(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            if isinstance(form, UserCommentForm):
                comment.user = request.user
            comment.flower = self.get_object()
            comment.save()
            return redirect(comment.get_absolute_url())
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return render(request, self.template_name, context)


class FlowerCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = FlowerCreation
    template_name = 'flowers/flower_create.html'

    def form_valid(self, form):
        flower = form.save(commit=False)
        flower.seller = self.request.user
        flower.save()
        return redirect(flower.get_absolute_url())


class FlowerUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Flower
    fields = ['title', 'description', 'price', 'cover', ]
    template_name = 'flowers/flower_update.html'

    def test_func(self):
        obj = self.get_object()
        return obj.seller == self.request.user

    # def form_valid(self, form):
    #     flower = form.save(commit=False)
    #     flower.seller = self.request.user
    #     flower.save()
    #     return redirect(flower.get_absolute_url())


class FlowerDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Flower
    template_name = 'flowers/flower_delete.html'
    success_url = reverse_lazy('flower_list')

    def test_func(self):
        obj = self.get_object()
        return obj.seller.username == self.request.user.username

pages/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


# Create your views here.

class HomePageView(TemplateView):
    template_name = 'home.html'

flowers/templates/flowers/flower_create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block page_title %} افزودن گل جدید{% endblock %}
{% block content %}
    <section class="module">
        <div class="container" dir="rtl">
            <div class="row">
                <div class="col-sm-5 col-sm-offset-1 mb-sm-40"
                     style="margin-left: 25%;box-shadow: 0px 11px 20px 3px #8ea99554;border-radius: 5px;">
                    <h4 class="font-alt">گیاه جدید</h4>
                    <hr class="divider-w mb-10">
                    <form class="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {#                    {{ form|crispy }}#}
                        {{ form.title|as_crispy_field }}
                        <div id="div_id_seller" class="form-group">






                        </div>
                        {{ form.description|as_crispy_field }}
                        {{ form.price|as_crispy_field }}
                        {{ form.cover|as_crispy_field }}
                        {#                  <div class="form-group">#}
                        {#                      {{ form.username|as_crispy_field  }}#}
                        {#                    <input class="form-control" id="username" type="text" name="username" placeholder="Username"/>#}
                        {#                  </div>#}
                        {#                  <div class="form-group">#}
                        {#                      {{ form.password|as_crispy_field  }}#}
                        {#                    <input class="form-control" id="password" type="password" name="password" placeholder="Password"/>#}
                        {#                  </div>#}
                        <div class="form-group">

                            <button class="btn btn-round btn-b" type="submit">افزودن</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

flowers/templates/flowers/flower_delete.html
{% extends '_base.html' %}

{% block page_title %}افزودن گل {{ flower.title }}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="module" xmlns="http://www.w3.org/1999/html">
          <div class="container" dir="rtl">
            <div class="row">
              <div class="col-sm-5 col-sm-offset-1 mb-sm-40" style="margin-left: 25%;box-shadow: 0px 11px 20px 3px #8ea99554;border-radius: 5px;">
                <h4 class="font-alt">حذف گل</h4>
                <hr class="divider-w mb-10">
                <form class="form" action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                  <div class="form-group">
                      <h3>آیا از حذف گل {{ flower.title }} مطمئن هستید ؟ </h3>
                    <button class="btn btn-round btn-b" type="submit">بله</button>
                      <a href=" {{ flower.get_absolute_url }} "><input type="button" class="btn btn-round btn-b" value="انصراف"></a>
                  </div>

                </form>
              </div>
            </div>
          </div>
        </section>




{% endblock %}

flowers/templates/flowers/flower_detail.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load flower_tags %}

{% block page_title %}جزییات گل {{ flower.title }}{% endblock %}
{% block content %}

    <section class="module">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 mb-sm-40"><a class="gallery">
                    {% if flower.cover %}
                        <img src="{{ flower.cover.url }}" alt="Accessories Pack"/>
                    {% else %}
                        <img src="{% static 'assets/images/shop/No_Cover.jpg' %}" alt="Accessories Pack"/>
                    {% endif %}

                </a>

                </div>
                <div class="col-sm-6" dir="rtl">
                    <div class="row">
                        <div class="col-sm-8">
                            <h1 class="product-title font-alt">{{ flower.title|is_english }}</h1>
                        </div>
                    </div>

                    <div class="row mb-20">
                        <div class="col-sm-8">
                            <div class="description">
                                <p>{{ flower.description }}</p>
                                <p>ایجاد کننده : {{ flower.seller }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-8">
                        <div class="col-sm-8">
                            <div class="price font-alt"><span class="amount">{{ flower.price }} تومان </span></div>
                        </div>
                    </div>

                    <div class="row mb-20">
                        <div class="col-sm-8"><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span>
                        </div>
                    </div>
                    <div class="row mb-20">
                        <div class="col-sm-8"><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span>
                        </div>
                    </div>
                    <div class="row mb-20">
                        <div class="col-sm-8"><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span>
                        </div>
                    </div>
                    <div class="row mb-20">
                        <div class="col-sm-8"><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span>
                        </div>
                    </div>
                    <div class="row mb-20">
                        <div class="col-sm-8"><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star"></i></span><span><i
                                class="fa fa-star star"></i></span><span><i class="fa fa-star star-off"></i></span>
                        </div>
                    </div>
                    {% if flower.seller.username == user.username %}
                        <div class="row mb-20">
                            <div class="col-sm-8"><a class="btn btn-lg btn-block btn-round btn-b"
                                                     href="{% url 'flower_update' flower.id %}">ویرایش</a></div>
                            <div class="col-sm-8 " style="margin-top: 15px"><a
                                    class="btn btn-lg btn-block btn-round btn-b"
                                    href="{% url 'flower_delete' flower.id %}">حذف</a>
                            </div>
                        </div>
                    {% endif %}

                </div>


            </div>
            <div class="col-sm-12 d-flex justify-content-center card shadow my-3 p-5 w-sm-75 w-100 mt-30" dir="rtl">
                <div class="d-flex justify-content-center" style="box-shadow: 1px 1px 20px 1px #8888886b;" dir="rtl">
                    <div class="card shadow my-3 p-5 w-sm-75 w-100" style="padding: 3rem"
                    ">
                    <h2 class="mb-5">نظرات:</h2>
                    {% for comment in  comments %}
                        <div style="border-bottom: inset;">
                            {% if comment.is_active %}
                                <h4 class="mb-3">{{ comment.get_author_name }} : </h4>
                                {% if comment.recommend %}
                                    <p>خرید این گل را توصیه میکنم</p>
                                {% else %}
                                    <p>خرید این گل را توصیه نمیکنم</p>
                                {% endif %}
                                <p style="font-size: medium;line-height: 3rem;;">{{ comment.text|linebreaks }}</p>

                            {% endif %}
                        </div>
                    {% endfor %}


                </div>
            </div>

            <div class="mt-20 " dir="rtl" style="box-shadow: 1px 1px 20px 1px #8888886b;padding: 3rem">
                <div class="comment-form mt-30" dir="rtl">
                    <h4 class="comment-form-title font-alt">نظر خود را وارد کنید :</h4>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        {#                        <div class="row">#}
                        {#                            <div class="col-sm-4">#}
                        {#                                <div class="form-group">#}
                        {#                                    <div id="div_id_recommend" class="form-check">#}
                        {#                                        <label for="id_recommend" class="form-check-label">#}
                        {#                                            توصیه میکنم#}
                        {#                                        </label>#}
                        {#                                        <input type="checkbox" name="recommend" class="checkboxinput form-check-input" style="margin: 4px 30px 0;"#}
                        {#                                               id="id_recommend" checked="">#}
                        {#                                    </div>#}
                        {#                                </div>#}
                        {#                            </div>#}
                        {#                            <div class="col-sm-4">#}
                        {#                                <div class="form-group">#}
                        {#                                    <label class="sr-only" for="email">Name</label>#}
                        {#                                    <input class="form-control" id="email" type="text" name="email"#}
                        {#                                           placeholder="ایمیل"/>#}
                        {#                                </div>#}
                        {#                            </div>#}
                        {#                            <div class="col-sm-4">#}
                        {#                                <div class="form-group">#}
                        {#                                    <label class="sr-only" for="name">نام</label>#}
                        {#                                    <input class="form-control" id="name" type="text" name="name" placeholder="نام"/>#}
                        {#                                </div>#}
                        {#                            </div>#}
                        {#                            <div class="col-sm-12">#}
                        {#                                <div class="form-group">#}
                        {#                                    <textarea class="form-control" id="" name="" rows="4"#}
                        {#                                              placeholder="متن نظر"></textarea>#}
                        {#                                </div>#}
                        {#                            </div>#}
                        {#                            <div class="col-sm-12">#}
                        <button class="btn btn-round btn-success" type="submit">ارسال نظر</button>
                        {#                            </div>#}


                    </form>
                </div>
            </div>
        </div>

    </section>



{% endblock %}

flowers/templates/flowers/flower_list.html
{% extends '_base.html' %}
{% load static %}
{% load flower_tags %}
{% block page_title %}لیست گلها{% endblock %}
{% block content %}
    <section class="module-small" style="padding: 146px 0;">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <h2 class="module-title" style="letter-spacing: 0;">جدیدترین گلها</h2>
                </div>
            </div>
            <div class="row multi-columns-row">
                {% for flower in flowers %}
                    <a href="{{ flower.get_absolute_url }}">
                        <div class="col-sm-6 col-md-3 col-lg-3">
                            <div class="shop-item">
                                <div class="shop-item-image" style="height: 35rem;">
                                    {% if flower.cover %}
                                        <img src="{{ flower.cover.url }}" alt="Accessories Pack"/>
                                    {% else %}
                                        <img src="{% static 'assets/images/shop/No_Cover.jpg' %}"
                                             alt="Accessories Pack"/>
                                    {% endif %}
                                    <div class="shop-item-detail"><a href="{{ flower.get_absolute_url }}"
                                                                     class="btn btn-round btn-b"><span
                                            class="icon-basket">{{ flower.title }}</span></a>
                                    </div>
                                </div>
                                <h4 class="shop-item-title font-alt"><a href="{{ flower.get_absolute_url }}">{{ flower.description }}</a></h4>
                                <p>{{ flower.price }}</p>
                            </div>
                        </div>
                    </a>

                {% endfor %}

            </div>
            <div class="row mt-30">
                <div class="col-sm-12 align-center">
                    <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                    {% endif %}
                </ul>
            </nav>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

flowers/templates/flowers/flower_update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block page_title %} افزودن گل جدید{% endblock %}
{% block content %}
    <section class="module">
        <div class="container" dir="rtl">
            <div class="row">
                <div class="col-sm-5 col-sm-offset-1 mb-sm-40"
                     style="margin-left: 25%;box-shadow: 0px 11px 20px 3px #8ea99554;border-radius: 5px;">
                    <h4 class="font-alt">گیاه جدید</h4>
                    <hr class="divider-w mb-10">
                    <form class="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                       <div class="form-group">

                            <button class="btn btn-round btn-b" type="submit">ویرایش</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/home.html
{% extends '_base.html' %}

{% block page_title %}Home Page{% endblock %}
{% block content %}

     <!-- ======= slide Section ======= -->
<section class="home-section home-fade home-full-height" id="home">
        <div class="hero-slider">
          <ul class="slides">
            <li class="bg-dark-30 bg-dark shop-page-header" style="background-image:url(/static/assets/images/shop/slider1.jpg);">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-1">This is Titan</div>
                  <div class="font-alt mb-30 titan-title-size-4"> Summer 2022</div>
                  <div class="font-alt mb-40 titan-title-size-1">گلها موسیقی خاک هستند از لبهای زمین که بدون صدا صحبت میکنند</div><a class="section-scroll btn btn-border-w btn-round" href="{% url 'flower_list' %}">لیست محصولات</a>
                </div>
              </div>
            </li>
            <li class="bg-dark-30 bg-dark shop-page-header" style="background-image:url(/static/assets/images/shop/slider2.jpg);">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-1"> This is Titan</div>
                  <div class="font-alt mb-40 titan-title-size-1">تمام گلهایی که فردا میرویند در بذرهای امروز هستند</div><a class="section-scroll btn btn-border-w btn-round" href="{% url 'flower_list' %}">لیست محصولات</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </section>

{% endblock %}